export { prisma } from "./client.js";
export type { PrismaClient } from "../generated/prisma/client.js";
export {
  UserRole,
  OrganizationType,
  OrganizationTier,
  ProductCategory,
  ProductStatus,
  ServiceCaseType,
  ServiceCaseStatus,
  CasePriority,
  TicketStatus,
  TicketUrgency,
  QuoteStatus,
  ApprovalMethod,
  QuoteLineItemType,
  GstType,
  InvoiceStatus,
  PaymentStatus,
  PaymentMethod,
  DispatchDirection,
  DispatchStatus,
  RepairEventType,
  CaseActivityType,
  CaseActivityVisibility,
  ActorType,
  AuditAction,
  AttachmentCategory,
  SlaEventType,
} from "../generated/prisma/client.js";
